# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 789e7c041d0246337b38f861a9b9444ac5cc5c33108bc6d723d6e0e0698a8426539c58d7cdffb27898b477832a6a4e7ae1ce787b789073da4730728042ece8a9

test:
  secret_key_base: 81b4557821dc19d3070eba178336f59e1831153cb6f513c6585f4e93ef6d997d35a399cca56d29b79c29d6156e4727117aaa97765e82d3910e1529f702b26530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
